local defaultShops = {
    ["19ed14ff-dfb1-4cdb-b34a-f161699842c6"] = {
        ["name"] = "Miscellaneous",
        ["listings"] = {
            ["Base.AlarmClock2"] = {
                ["item"] = "Base.AlarmClock2",
                ["price"] = 3,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = {
                    ["hour"] = 2,
                    ["minute"] = 20,
                    ["alarmSet"] = true,
                },
            },
            ["Base.Battery"] = {
                ["item"] = "Base.Battery",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = {
                },
            },
            ["Base.WristWatch_Left_DigitalBlack"] = {
                ["item"] = "Base.WristWatch_Left_DigitalBlack",
                ["price"] = 15,
                ["buybackRate"] = 0.05,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = {
                    ["hour"] = 1,
                    ["minute"] = 0,
                    ["alarmSet"] = false,
                },
            },
            ["Base.Bowl"] = {
                ["item"] = "Base.Bowl",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 9,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.PetrolCan"] = {
                ["item"] = "Base.PetrolCan",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["customWeight"] = true,
                },
            },
            ["Base.Generator"] = {
                ["item"] = "Base.Generator",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Hairgel"] = {
                ["item"] = "Base.Hairgel",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.ElectronicsMag4"] = {
                ["item"] = "Base.ElectronicsMag4",
                ["price"] = 100,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["numberOfPages"] = -1,
                    ["alreadyReadPages"] = 0,
                    ["canBeWrite"] = false,
                },
            },
            ["Base.Lighter"] = {
                ["item"] = "Base.Lighter",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.PipeBomb"] = {
                ["item"] = "Base.PipeBomb",
                ["price"] = 0,
                ["buybackRate"] = 0,
                ["stock"] = 0,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["maxDamage"] = 0,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 1,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.PipeBombSensorV3"] = {
                ["item"] = "Base.PipeBombSensorV3",
                ["price"] = 0,
                ["buybackRate"] = 0,
                ["stock"] = 0,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["maxDamage"] = 0,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 1,
                    ["explosionTimer"] = 5,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Woodglue"] = {
                ["item"] = "Base.Woodglue",
                ["price"] = 0,
                ["buybackRate"] = 0,
                ["stock"] = 0,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Scissors"] = {
                ["item"] = "Base.Scissors",
                ["price"] = 0,
                ["buybackRate"] = 0,
                ["stock"] = 0,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.8999999761581421,
                    ["maxDamage"] = 0.10000000149011612,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
        },
        ["ID"] = "19ed14ff-dfb1-4cdb-b34a-f161699842c6",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 5,
        ["locations"] = {},
    },

    ["8d7e0c39-7aba-410a-929e-5f9548e3e170"] = {
        ["name"] = "Medical",
        ["listings"] = {
            ["Base.Bandaid"] = {
                ["item"] = "Base.Bandaid",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Bandage"] = {
                ["item"] = "Base.Bandage",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.AlcoholBandage"] = {
                ["item"] = "Base.AlcoholBandage",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Disinfectant"] = {
                ["item"] = "Base.Disinfectant",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Antibiotics"] = {
                ["item"] = "Base.Antibiotics",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.11224330961704254,
                    ["lastAged"] = 14.574344635009766,
                    ["calories"] = 0,
                    ["proteins"] = 0,
                    ["lipids"] = 0,
                    ["carbohydrates"] = 0,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = 0,
                    ["baseHunger"] = 0,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.PillsAntiDep"] = {
                ["item"] = "Base.PillsAntiDep",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.PillsBeta"] = {
                ["item"] = "Base.PillsBeta",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Pills"] = {
                ["item"] = "Base.Pills",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.FirstAidKit"] = {
                ["item"] = "Base.FirstAidKit",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["weightReduction"] = 5,
                },
            },
            ["Base.HospitalGown"] = {
                ["item"] = "Base.HospitalGown",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
        },
        ["ID"] = "8d7e0c39-7aba-410a-929e-5f9548e3e170",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 140,
        ["locations"] = {},
    },
    ["8703654d-a899-4798-a454-234af1d01efe"] = {
        ["name"] = "Guns",
        ["listings"] = {
            ["Base.223Box"] = {
                ["item"] = "Base.223Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.308Box"] = {
                ["item"] = "Base.308Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Bullets38Box"] = {
                ["item"] = "Base.Bullets38Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Bullets44Box"] = {
                ["item"] = "Base.Bullets44Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Bullets45Box"] = {
                ["item"] = "Base.Bullets45Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.556Box"] = {
                ["item"] = "Base.556Box",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Bullets9mmBox"] = {
                ["item"] = "Base.Bullets9mmBox",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.ShotgunShellsBox"] = {
                ["item"] = "Base.ShotgunShellsBox",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.44Clip"] = {
                ["item"] = "Base.44Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.M14Clip"] = {
                ["item"] = "Base.M14Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.556Clip"] = {
                ["item"] = "Base.556Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.45Clip"] = {
                ["item"] = "Base.45Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.9mmClip"] = {
                ["item"] = "Base.9mmClip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.223Clip"] = {
                ["item"] = "Base.223Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.308Clip"] = {
                ["item"] = "Base.308Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Pistol3"] = {
                ["item"] = "Base.Pistol3",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["ClipSize"] = 15,
                    ["maxDamage"] = 1.899999976158142,
                    ["RecoilDelay"] = 32,
                    ["aimingTime"] = 30,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 20,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.DoubleBarrelShotgun"] = {
                ["item"] = "Base.DoubleBarrelShotgun",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 9,
                    ["maxDamage"] = 2.700000047683716,
                    ["RecoilDelay"] = 50,
                    ["aimingTime"] = 20,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 80,
                    ["minAngle"] = 0.8999999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Shotgun"] = {
                ["item"] = "Base.Shotgun",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 7,
                    ["maxDamage"] = 2.200000047683716,
                    ["RecoilDelay"] = 50,
                    ["aimingTime"] = 20,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 70,
                    ["minAngle"] = 0.8999999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.AssaultRifle2"] = {
                ["item"] = "Base.AssaultRifle2",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["ClipSize"] = 20,
                    ["maxDamage"] = 2,
                    ["aimingTime"] = 25,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 50,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.AssaultRifle"] = {
                ["item"] = "Base.AssaultRifle",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 11,
                    ["maxDamage"] = 1.399999976158142,
                    ["aimingTime"] = 25,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 20,
                    ["minAngle"] = 0.9649999737739563,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Pistol2"] = {
                ["item"] = "Base.Pistol2",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 8,
                    ["ClipSize"] = 15,
                    ["maxDamage"] = 1.399999976158142,
                    ["RecoilDelay"] = 25,
                    ["aimingTime"] = 20,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 40,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Revolver_Short"] = {
                ["item"] = "Base.Revolver_Short",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 6,
                    ["maxDamage"] = 1.2000000476837158,
                    ["RecoilDelay"] = 17,
                    ["aimingTime"] = 10,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 65,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Revolver"] = {
                ["item"] = "Base.Revolver",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 9,
                    ["ClipSize"] = 15,
                    ["maxDamage"] = 1.600000023841858,
                    ["RecoilDelay"] = 25,
                    ["aimingTime"] = 25,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 30,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Pistol"] = {
                ["item"] = "Base.Pistol",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 7,
                    ["ClipSize"] = 15,
                    ["maxDamage"] = 1,
                    ["RecoilDelay"] = 20,
                    ["aimingTime"] = 15,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 50,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.VarmintRifle"] = {
                ["item"] = "Base.VarmintRifle",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["maxDamage"] = 1.2999999523162842,
                    ["RecoilDelay"] = 90,
                    ["aimingTime"] = 30,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 27,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.HuntingRifle"] = {
                ["item"] = "Base.HuntingRifle",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 10,
                    ["maxDamage"] = 2,
                    ["RecoilDelay"] = 100,
                    ["aimingTime"] = 40,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 25,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Revolver_Long"] = {
                ["item"] = "Base.Revolver_Long",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 11,
                    ["ClipSize"] = 15,
                    ["maxDamage"] = 1.899999976158142,
                    ["RecoilDelay"] = 32,
                    ["aimingTime"] = 40,
                    ["reloadTime"] = 30,
                    ["hitChance"] = 20,
                    ["minAngle"] = 0.949999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.ShotgunSawnoff"] = {
                ["item"] = "Base.ShotgunSawnoff",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 6,
                    ["ClipSize"] = 6,
                    ["maxDamage"] = 2.200000047683716,
                    ["RecoilDelay"] = 50,
                    ["aimingTime"] = 20,
                    ["reloadTime"] = 25,
                    ["hitChance"] = 100,
                    ["minAngle"] = 0.6570000052452087,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Glasses_Shooting"] = {
                ["item"] = "Base.Glasses_Shooting",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.HolsterSimple"] = {
                ["item"] = "Base.HolsterSimple",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Gloves_LeatherGloves"] = {
                ["item"] = "Base.Gloves_LeatherGloves",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.HolsterDouble"] = {
                ["item"] = "Base.HolsterDouble",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
        },
        ["ID"] = "8703654d-a899-4798-a454-234af1d01efe",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["57094824-711a-436a-869d-030e23ebb3b9"] = {
        ["name"] = "Food and Drink",
        ["listings"] = {
            ["Base.WaterBottleFull"] = {
                ["item"] = "Base.WaterBottleFull",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["customWeight"] = true,
                },
            },
            ["Base.Apple"] = {
                ["item"] = "Base.Apple",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2642940878868103,
                    ["lastAged"] = 18.223642349243164,
                    ["calories"] = 95,
                    ["proteins"] = 0.4699999988079071,
                    ["lipids"] = 0.3100000023841858,
                    ["carbohydrates"] = 25.1299991607666,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.1599999964237213,
                    ["baseHunger"] = -0.1599999964237213,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.07000000029802322,
                    ["IsCookable"] = false,
                    ["Chef"] = "Claire Cho",
                    ["OffAge"] = 5,
                    ["OffAgeMax"] = 8,
                },
            },
            ["Base.Bread"] = {
                ["item"] = "Base.Bread",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.26842185854911804,
                    ["lastAged"] = 18.322635650634766,
                    ["calories"] = 532,
                    ["proteins"] = 17.700000762939453,
                    ["lipids"] = 6.659999847412109,
                    ["carbohydrates"] = 99,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.30000001192092896,
                    ["baseHunger"] = -0.30000001192092896,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                    ["OffAge"] = 3,
                    ["OffAgeMax"] = 6,
                },
            },
            ["Base.BeerBottle"] = {
                ["item"] = "Base.BeerBottle",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.26879701018333435,
                    ["lastAged"] = 18.331634521484375,
                    ["calories"] = 170,
                    ["proteins"] = 0,
                    ["lipids"] = 0,
                    ["carbohydrates"] = 39,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.09000000357627869,
                    ["baseHunger"] = -0.09000000357627869,
                    ["unhappyChange"] = -16,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.12999999523162842,
                    ["IsCookable"] = false,
                },
            },
            ["Base.BeefJerky"] = {
                ["item"] = "Base.BeefJerky",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.26908883452415466,
                    ["lastAged"] = 18.338634490966797,
                    ["calories"] = 100,
                    ["proteins"] = 1,
                    ["lipids"] = 1,
                    ["carbohydrates"] = 6,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.20000000298023224,
                    ["baseHunger"] = -0.20000000298023224,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.Banana"] = {
                ["item"] = "Base.Banana",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2694084048271179,
                    ["lastAged"] = 18.34630012512207,
                    ["calories"] = 105,
                    ["proteins"] = 1.2899999618530273,
                    ["lipids"] = 0.38999998569488525,
                    ["carbohydrates"] = 26.950000762939453,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.1599999964237213,
                    ["baseHunger"] = -0.1599999964237213,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.05000000074505806,
                    ["IsCookable"] = false,
                    ["OffAge"] = 5,
                    ["OffAgeMax"] = 7,
                },
            },
            ["Base.CannedChili"] = {
                ["item"] = "Base.CannedChili",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2710619270801544,
                    ["lastAged"] = 18.385963439941406,
                    ["calories"] = 260,
                    ["proteins"] = 16,
                    ["lipids"] = 7,
                    ["carbohydrates"] = 33,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = 0,
                    ["baseHunger"] = 0,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.Crisps2"] = {
                ["item"] = "Base.Crisps2",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2730490267276764,
                    ["lastAged"] = 18.43362808227539,
                    ["calories"] = 720,
                    ["proteins"] = 4.5,
                    ["lipids"] = 45,
                    ["carbohydrates"] = 72,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.15000000596046448,
                    ["baseHunger"] = -0.15000000596046448,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.ChickenNuggets"] = {
                ["item"] = "Base.ChickenNuggets",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.27343809604644775,
                    ["lastAged"] = 18.442960739135742,
                    ["calories"] = 230,
                    ["proteins"] = 26.44099998474121,
                    ["lipids"] = 8.100000381469727,
                    ["carbohydrates"] = 10.199999809265137,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.10000000149011612,
                    ["baseHunger"] = -0.10000000149011612,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                    ["OffAge"] = 5,
                    ["OffAgeMax"] = 8,
                },
            },
            ["Base.Corn"] = {
                ["item"] = "Base.Corn",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2738688290119171,
                    ["lastAged"] = 18.453292846679688,
                    ["calories"] = 88,
                    ["proteins"] = 4.679999828338623,
                    ["lipids"] = 1.9299999475479126,
                    ["carbohydrates"] = 26.739999771118164,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.14000000059604645,
                    ["baseHunger"] = -0.14000000059604645,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.03999999910593033,
                    ["IsCookable"] = false,
                    ["OffAge"] = 5,
                    ["OffAgeMax"] = 8,
                },
            },
            ["Base.Chocolate"] = {
                ["item"] = "Base.Chocolate",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2742995619773865,
                    ["lastAged"] = 18.463624954223633,
                    ["calories"] = 850,
                    ["proteins"] = 10,
                    ["lipids"] = 66,
                    ["carbohydrates"] = 110,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.20000000298023224,
                    ["baseHunger"] = -0.20000000298023224,
                    ["unhappyChange"] = -10,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.DoughnutFrosted"] = {
                ["item"] = "Base.DoughnutFrosted",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.27486929297447205,
                    ["lastAged"] = 18.477291107177734,
                    ["calories"] = 180,
                    ["proteins"] = 3,
                    ["lipids"] = 15,
                    ["carbohydrates"] = 35,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.07000000029802322,
                    ["baseHunger"] = -0.07000000029802322,
                    ["unhappyChange"] = -15,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                    ["OffAge"] = 3,
                    ["OffAgeMax"] = 5,
                },
            },
            ["Base.Orange"] = {
                ["item"] = "Base.Orange",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.27606433629989624,
                    ["lastAged"] = 18.505956649780273,
                    ["calories"] = 65,
                    ["proteins"] = 1,
                    ["lipids"] = 0.30000001192092896,
                    ["carbohydrates"] = 16.270000457763672,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.11999999731779099,
                    ["baseHunger"] = -0.11999999731779099,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.07999999821186066,
                    ["IsCookable"] = false,
                    ["OffAge"] = 6,
                    ["OffAgeMax"] = 9,
                },
            },
            ["Base.PopBottle"] = {
                ["item"] = "Base.PopBottle",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.27650898694992065,
                    ["lastAged"] = 18.51662254333496,
                    ["calories"] = 400,
                    ["proteins"] = 0,
                    ["lipids"] = 0,
                    ["carbohydrates"] = 104,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.11999999731779099,
                    ["baseHunger"] = -0.11999999731779099,
                    ["unhappyChange"] = -10,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -0.8500000238418579,
                    ["IsCookable"] = false,
                },
            },
            ["Base.PeanutButter"] = {
                ["item"] = "Base.PeanutButter",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2771620452404022,
                    ["lastAged"] = 18.53228759765625,
                    ["calories"] = 2660,
                    ["proteins"] = 84,
                    ["lipids"] = 224,
                    ["carbohydrates"] = 128,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.25,
                    ["baseHunger"] = -0.25,
                    ["unhappyChange"] = -15,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.Pickles"] = {
                ["item"] = "Base.Pickles",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2776206135749817,
                    ["lastAged"] = 18.54328727722168,
                    ["calories"] = 5,
                    ["proteins"] = 0,
                    ["lipids"] = 0,
                    ["carbohydrates"] = 1,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.05000000074505806,
                    ["baseHunger"] = -0.05000000074505806,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                },
            },
            ["Base.Watermelon"] = {
                ["item"] = "Base.Watermelon",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.27823200821876526,
                    ["lastAged"] = 18.557952880859375,
                    ["calories"] = 1355,
                    ["proteins"] = 27.559999465942383,
                    ["lipids"] = 6.78000020980835,
                    ["carbohydrates"] = 341.1099853515625,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.6000000238418579,
                    ["baseHunger"] = -0.6000000238418579,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -1.399999976158142,
                    ["IsCookable"] = false,
                    ["OffAge"] = 6,
                    ["OffAgeMax"] = 8,
                },
            },
            ["Base.TinOpener"] = {
                ["item"] = "Base.TinOpener",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Kettle"] = {
                ["item"] = "Base.Kettle",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Pan"] = {
                ["item"] = "Base.Pan",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 0.5,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GridlePan"] = {
                ["item"] = "Base.GridlePan",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 0.44999998807907104,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.IcePick"] = {
                ["item"] = "Base.IcePick",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.800000011920929,
                    ["maxDamage"] = 0.8999999761581421,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.MeatCleaver"] = {
                ["item"] = "Base.MeatCleaver",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1,
                    ["maxDamage"] = 0.800000011920929,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.KitchenKnife"] = {
                ["item"] = "Base.KitchenKnife",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.8999999761581421,
                    ["maxDamage"] = 0.699999988079071,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.RollingPin"] = {
                ["item"] = "Base.RollingPin",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 0.5,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.BreadKnife"] = {
                ["item"] = "Base.BreadKnife",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1,
                    ["maxDamage"] = 0.4000000059604645,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Waffles"] = {
                ["item"] = "Base.Waffles",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2972732484340668,
                    ["lastAged"] = 19.014698028564453,
                    ["calories"] = 80,
                    ["proteins"] = 3,
                    ["lipids"] = 4,
                    ["carbohydrates"] = 13,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.15000000596046448,
                    ["baseHunger"] = -0.15000000596046448,
                    ["unhappyChange"] = -10,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                    ["OffAge"] = 3,
                    ["OffAgeMax"] = 5,
                },
            },
            ["Base.PeanutButterSandwich"] = {
                ["item"] = "Base.PeanutButterSandwich",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2981625497341156,
                    ["lastAged"] = 19.036029815673828,
                    ["calories"] = 250,
                    ["proteins"] = 7,
                    ["lipids"] = 25,
                    ["carbohydrates"] = 14,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.17000000178813934,
                    ["baseHunger"] = -0.17000000178813934,
                    ["unhappyChange"] = -10,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = 0,
                    ["IsCookable"] = false,
                    ["OffAge"] = 2,
                    ["OffAgeMax"] = 4,
                },
            },
            ["Base.Milk"] = {
                ["item"] = "Base.Milk",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["age"] = 0.2985377907752991,
                    ["lastAged"] = 19.04503059387207,
                    ["calories"] = 110,
                    ["proteins"] = 8,
                    ["lipids"] = 2.5,
                    ["carbohydrates"] = 13,
                    ["fatigueChange"] = 0,
                    ["endChange"] = 0,
                    ["hungChange"] = -0.10000000149011612,
                    ["baseHunger"] = -0.10000000149011612,
                    ["unhappyChange"] = 0,
                    ["boredomChange"] = 0,
                    ["thirstChange"] = -1,
                    ["IsCookable"] = false,
                    ["OffAge"] = 4,
                    ["OffAgeMax"] = 7,
                },
            },
        },
        ["ID"] = "57094824-711a-436a-869d-030e23ebb3b9",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["32383a4f-0463-45af-8402-fcd016066b25"] = {
        ["name"] = "Building",
        ["listings"] = {
            ["Base.BallPeenHammer"] = {
                ["item"] = "Base.BallPeenHammer",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.ClubHammer"] = {
                ["item"] = "Base.ClubHammer",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Hammer"] = {
                ["item"] = "Base.Hammer",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.WoodAxe"] = {
                ["item"] = "Base.WoodAxe",
                ["price"] = 70,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 3,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Saw"] = {
                ["item"] = "Base.Saw",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.BlowTorch"] = {
                ["item"] = "Base.BlowTorch",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["customWeight"] = true,
                },
            },
            ["Base.WeldingMask"] = {
                ["item"] = "Base.WeldingMask",
                ["price"] = 70,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.NailsBox"] = {
                ["item"] = "Base.NailsBox",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.SheetMetal"] = {
                ["item"] = "Base.SheetMetal",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.Plank"] = {
                ["item"] = "Base.Plank",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.2999999523162842,
                    ["maxDamage"] = 0.6000000238418579,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.75,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.SmallSheetMetal"] = {
                ["item"] = "Base.SmallSheetMetal",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                },
            },
            ["Base.WeldingRods"] = {
                ["item"] = "Base.WeldingRods",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["customWeight"] = true,
                },
            },
            ["Base.Sledgehammer"] = {
                ["item"] = "Base.Sledgehammer",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 3,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Sledgehammer2"] = {
                ["item"] = "Base.Sledgehammer2",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 3,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.PipeWrench"] = {
                ["item"] = "Base.PipeWrench",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Screwdriver"] = {
                ["item"] = "Base.Screwdriver",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.8500000238418579,
                    ["maxDamage"] = 0.699999988079071,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Wrench"] = {
                ["item"] = "Base.Wrench",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Plunger"] = {
                ["item"] = "Base.Plunger",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 0.5,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
        },
        ["ID"] = "32383a4f-0463-45af-8402-fcd016066b25",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
    },
    ["a36d83e5-8542-436f-8fb1-65784f08d3bf"] = {
        ["name"] = "Weapons",
        ["listings"] = {
            ["Base.HuntingKnife"] = {
                ["item"] = "Base.HuntingKnife",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.8999999761581421,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Katana"] = {
                ["item"] = "Base.Katana",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.399999976158142,
                    ["maxDamage"] = 8,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.LeadPipe"] = {
                ["item"] = "Base.LeadPipe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.149999976158142,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.699999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Machete"] = {
                ["item"] = "Base.Machete",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.2300000190734863,
                    ["maxDamage"] = 3,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.699999988079071,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Axe"] = {
                ["item"] = "Base.Axe",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.2000000476837158,
                    ["maxDamage"] = 2,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.7200000286102295,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Crowbar"] = {
                ["item"] = "Base.Crowbar",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.25,
                    ["maxDamage"] = 1.149999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.75,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.HandAxe"] = {
                ["item"] = "Base.HandAxe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 1.5,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.HandScythe"] = {
                ["item"] = "Base.HandScythe",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.100000023841858,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.PickAxe"] = {
                ["item"] = "Base.PickAxe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 2.200000047683716,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.SnowShovel"] = {
                ["item"] = "Base.SnowShovel",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 1.899999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.BaseballBat"] = {
                ["item"] = "Base.BaseballBat",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.25,
                    ["maxDamage"] = 1.100000023841858,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.75,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Golfclub"] = {
                ["item"] = "Base.Golfclub",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.4199999570846558,
                    ["maxDamage"] = 1,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.HockeyStick"] = {
                ["item"] = "Base.HockeyStick",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 0.699999988079071,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.IceHockeyStick"] = {
                ["item"] = "Base.IceHockeyStick",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 0.699999988079071,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.LeafRake"] = {
                ["item"] = "Base.LeafRake",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 0.4000000059604645,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Rake"] = {
                ["item"] = "Base.Rake",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 0.4000000059604645,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Shovel2"] = {
                ["item"] = "Base.Shovel2",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 1.899999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Shovel"] = {
                ["item"] = "Base.Shovel",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.600000023841858,
                    ["maxDamage"] = 1.899999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.8500000238418579,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["farming.HandShovel"] = {
                ["item"] = "farming.HandShovel",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 0.8999999761581421,
                    ["maxDamage"] = 0.4000000059604645,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
        },
        ["ID"] = "a36d83e5-8542-436f-8fb1-65784f08d3bf",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 0,
        ["locations"] = {},
    },
    ["66293eef-dfa4-4528-a3ad-d688227d7e73"] = {
        ["name"] = "Music",
        ["listings"] = {
            ["Base.GuitarElectricBassBlack"] = {
                ["item"] = "Base.GuitarElectricBassBlack",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.399999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GuitarElectricBlack"] = {
                ["item"] = "Base.GuitarElectricBlack",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GuitarElectricBassBlue"] = {
                ["item"] = "Base.GuitarElectricBassBlue",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.399999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GuitarElectricBlue"] = {
                ["item"] = "Base.GuitarElectricBlue",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GuitarElectricBassRed"] = {
                ["item"] = "Base.GuitarElectricBassRed",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.399999976158142,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.GuitarElectricRed"] = {
                ["item"] = "Base.GuitarElectricRed",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.350000023841858,
                    ["maxDamage"] = 1.2000000476837158,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.800000011920929,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Trumpet"] = {
                ["item"] = "Base.Trumpet",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.149999976158142,
                    ["maxDamage"] = 0.800000011920929,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6700000166893005,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Violin"] = {
                ["item"] = "Base.Violin",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1,
                    ["maxDamage"] = 0.4000000059604645,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.6499999761581421,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
            ["Base.Banjo"] = {
                ["item"] = "Base.Banjo",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 0,
                ["reselling"] = false,
                ["alwaysShow"] = false,
                ["fields"] = {
                    ["maxRange"] = 1.25,
                    ["maxDamage"] = 0.6000000238418579,
                    ["reloadTime"] = 0,
                    ["hitChance"] = 0,
                    ["minAngle"] = 0.75,
                    ["containsClip"] = false,
                    ["roundChambered"] = false,
                    ["jammed"] = false,
                },
            },
        },
        ["ID"] = "66293eef-dfa4-4528-a3ad-d688227d7e73",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
    },
}
return defaultShops