local defaultShops = {
    ["19ed14ff-dfb1-4cdb-b34a-f161699842c6"] = {
        ["name"] = "Miscellaneous",
        ["listings"] = {
            ["Base.AlarmClock2"] = {
                ["item"] = "Base.AlarmClock2",
                ["price"] = 3,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Battery"] = {
                ["item"] = "Base.Battery",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WristWatch_Left_DigitalBlack"] = {
                ["item"] = "Base.WristWatch_Left_DigitalBlack",
                ["price"] = 3,
                ["buybackRate"] = 0.05,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bowl"] = {
                ["item"] = "Base.Bowl",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PetrolCan"] = {
                ["item"] = "Base.PetrolCan",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Generator"] = {
                ["item"] = "Base.Generator",
                ["price"] = 100,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Hairgel"] = {
                ["item"] = "Base.Hairgel",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ElectronicsMag4"] = {
                ["item"] = "Base.ElectronicsMag4",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Lighter"] = {
                ["item"] = "Base.Lighter",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeBomb"] = {
                ["item"] = "Base.PipeBomb",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeBombSensorV3"] = {
                ["item"] = "Base.PipeBombSensorV3",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Woodglue"] = {
                ["item"] = "Base.Woodglue",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Scissors"] = {
                ["item"] = "Base.Scissors",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "19ed14ff-dfb1-4cdb-b34a-f161699842c6",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 5,
        ["locations"] = {},
    },

    ["8d7e0c39-7aba-410a-929e-5f9548e3e170"] = {
        ["name"] = "Medical",
        ["listings"] = {
            ["Base.Bandaid"] = {
                ["item"] = "Base.Bandaid",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bandage"] = {
                ["item"] = "Base.Bandage",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.AlcoholBandage"] = {
                ["item"] = "Base.AlcoholBandage",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Disinfectant"] = {
                ["item"] = "Base.Disinfectant",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Antibiotics"] = {
                ["item"] = "Base.Antibiotics",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PillsAntiDep"] = {
                ["item"] = "Base.PillsAntiDep",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PillsBeta"] = {
                ["item"] = "Base.PillsBeta",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pills"] = {
                ["item"] = "Base.Pills",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.FirstAidKit"] = {
                ["item"] = "Base.FirstAidKit",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HospitalGown"] = {
                ["item"] = "Base.HospitalGown",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "8d7e0c39-7aba-410a-929e-5f9548e3e170",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 140,
        ["locations"] = {},
    },
    ["8703654d-a899-4798-a454-234af1d01efe"] = {
        ["name"] = "Guns",
        ["listings"] = {
            ["Base.223Box"] = {
                ["item"] = "Base.223Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.308Box"] = {
                ["item"] = "Base.308Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets38Box"] = {
                ["item"] = "Base.Bullets38Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets44Box"] = {
                ["item"] = "Base.Bullets44Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets45Box"] = {
                ["item"] = "Base.Bullets45Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.556Box"] = {
                ["item"] = "Base.556Box",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets9mmBox"] = {
                ["item"] = "Base.Bullets9mmBox",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ShotgunShellsBox"] = {
                ["item"] = "Base.ShotgunShellsBox",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.44Clip"] = {
                ["item"] = "Base.44Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.M14Clip"] = {
                ["item"] = "Base.M14Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.556Clip"] = {
                ["item"] = "Base.556Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.45Clip"] = {
                ["item"] = "Base.45Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.9mmClip"] = {
                ["item"] = "Base.9mmClip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.223Clip"] = {
                ["item"] = "Base.223Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.308Clip"] = {
                ["item"] = "Base.308Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pistol3"] = {
                ["item"] = "Base.Pistol3",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.DoubleBarrelShotgun"] = {
                ["item"] = "Base.DoubleBarrelShotgun",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Shotgun"] = {
                ["item"] = "Base.Shotgun",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.AssaultRifle2"] = {
                ["item"] = "Base.AssaultRifle2",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.AssaultRifle"] = {
                ["item"] = "Base.AssaultRifle",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pistol2"] = {
                ["item"] = "Base.Pistol2",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Revolver_Short"] = {
                ["item"] = "Base.Revolver_Short",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Revolver"] = {
                ["item"] = "Base.Revolver",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pistol"] = {
                ["item"] = "Base.Pistol",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.VarmintRifle"] = {
                ["item"] = "Base.VarmintRifle",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HuntingRifle"] = {
                ["item"] = "Base.HuntingRifle",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Revolver_Long"] = {
                ["item"] = "Base.Revolver_Long",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ShotgunSawnoff"] = {
                ["item"] = "Base.ShotgunSawnoff",
                ["price"] = 60,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Glasses_Shooting"] = {
                ["item"] = "Base.Glasses_Shooting",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HolsterSimple"] = {
                ["item"] = "Base.HolsterSimple",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Gloves_LeatherGloves"] = {
                ["item"] = "Base.Gloves_LeatherGloves",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HolsterDouble"] = {
                ["item"] = "Base.HolsterDouble",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "8703654d-a899-4798-a454-234af1d01efe",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["57094824-711a-436a-869d-030e23ebb3b9"] = {
        ["name"] = "Food and Drink",
        ["listings"] = {
            ["Base.WaterBottleFull"] = {
                ["item"] = "Base.WaterBottleFull",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Apple"] = {
                ["item"] = "Base.Apple",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bread"] = {
                ["item"] = "Base.Bread",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BeerBottle"] = {
                ["item"] = "Base.BeerBottle",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BeefJerky"] = {
                ["item"] = "Base.BeefJerky",
                ["price"] = 7,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Banana"] = {
                ["item"] = "Base.Banana",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.CannedChili"] = {
                ["item"] = "Base.CannedChili",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Crisps2"] = {
                ["item"] = "Base.Crisps2",
                ["price"] = 3,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ChickenNuggets"] = {
                ["item"] = "Base.ChickenNuggets",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Corn"] = {
                ["item"] = "Base.Corn",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Chocolate"] = {
                ["item"] = "Base.Chocolate",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.DoughnutFrosted"] = {
                ["item"] = "Base.DoughnutFrosted",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Orange"] = {
                ["item"] = "Base.Orange",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PopBottle"] = {
                ["item"] = "Base.PopBottle",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PeanutButter"] = {
                ["item"] = "Base.PeanutButter",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pickles"] = {
                ["item"] = "Base.Pickles",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Watermelon"] = {
                ["item"] = "Base.Watermelon",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.TinOpener"] = {
                ["item"] = "Base.TinOpener",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Kettle"] = {
                ["item"] = "Base.Kettle",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pan"] = {
                ["item"] = "Base.Pan",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.GridlePan"] = {
                ["item"] = "Base.GridlePan",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.IcePick"] = {
                ["item"] = "Base.IcePick",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.MeatCleaver"] = {
                ["item"] = "Base.MeatCleaver",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.KitchenKnife"] = {
                ["item"] = "Base.KitchenKnife",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.RollingPin"] = {
                ["item"] = "Base.RollingPin",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BreadKnife"] = {
                ["item"] = "Base.BreadKnife",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Waffles"] = {
                ["item"] = "Base.Waffles",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PeanutButterSandwich"] = {
                ["item"] = "Base.PeanutButterSandwich",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Milk"] = {
                ["item"] = "Base.Milk",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "57094824-711a-436a-869d-030e23ebb3b9",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["32383a4f-0463-45af-8402-fcd016066b25"] = {
        ["name"] = "Building",
        ["listings"] = {
            ["Base.BallPeenHammer"] = {
                ["item"] = "Base.BallPeenHammer",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ClubHammer"] = {
                ["item"] = "Base.ClubHammer",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Hammer"] = {
                ["item"] = "Base.Hammer",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HammerStone"] = {
                ["item"] = "Base.HammerStone",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.WoodAxe"] = {
                ["item"] = "Base.WoodAxe",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Saw"] = {
                ["item"] = "Base.Saw",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BlowTorch"] = {
                ["item"] = "Base.BlowTorch",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WeldingMask"] = {
                ["item"] = "Base.WeldingMask",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.NailsBox"] = {
                ["item"] = "Base.NailsBox",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.SheetMetal"] = {
                ["item"] = "Base.SheetMetal",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Plank"] = {
                ["item"] = "Base.Plank",
                ["price"] = 5,
                ["buybackRate"] = 0,
                ["stock"] = 300,
                ["available"] = 300,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.SmallSheetMetal"] = {
                ["item"] = "Base.SmallSheetMetal",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 200,
                ["available"] = 200,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WeldingRods"] = {
                ["item"] = "Base.WeldingRods",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 400,
                ["available"] = 400,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Sledgehammer"] = {
                ["item"] = "Base.Sledgehammer",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Sledgehammer2"] = {
                ["item"] = "Base.Sledgehammer2",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeWrench"] = {
                ["item"] = "Base.PipeWrench",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Screwdriver"] = {
                ["item"] = "Base.Screwdriver",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Wrench"] = {
                ["item"] = "Base.Wrench",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Plunger"] = {
                ["item"] = "Base.Plunger",
                ["price"] = 2,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "32383a4f-0463-45af-8402-fcd016066b25",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
    },

    ["a36d83e5-8542-436f-8fb1-65784f08d3bf"] = {
        ["name"] = "Weapons",
        ["listings"] = {
            ["Base.HuntingKnife"] = {
                ["item"] = "Base.HuntingKnife",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Katana"] = {
                ["item"] = "Base.Katana",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.LeadPipe"] = {
                ["item"] = "Base.LeadPipe",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Machete"] = {
                ["item"] = "Base.Machete",
                ["price"] = 50,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Axe"] = {
                ["item"] = "Base.Axe",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Crowbar"] = {
                ["item"] = "Base.Crowbar",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HandAxe"] = {
                ["item"] = "Base.HandAxe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HandScythe"] = {
                ["item"] = "Base.HandScythe",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.PickAxe"] = {
                ["item"] = "Base.PickAxe",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.SnowShovel"] = {
                ["item"] = "Base.SnowShovel",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.BaseballBat"] = {
                ["item"] = "Base.BaseballBat",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Golfclub"] = {
                ["item"] = "Base.Golfclub",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HockeyStick"] = {
                ["item"] = "Base.HockeyStick",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.IceHockeyStick"] = {
                ["item"] = "Base.IceHockeyStick",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.LeafRake"] = {
                ["item"] = "Base.LeafRake",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Rake"] = {
                ["item"] = "Base.Rake",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Shovel2"] = {
                ["item"] = "Base.Shovel2",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Shovel"] = {
                ["item"] = "Base.Shovel",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["farming.HandShovel"] = {
                ["item"] = "farming.HandShovel",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassBlack"] = {
                ["item"] = "Base.GuitarElectricBassBlack",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBlack"] = {
                ["item"] = "Base.GuitarElectricBlack",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassBlue"] = {
                ["item"] = "Base.GuitarElectricBassBlue",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.GuitarElectricBlue"] = {
                ["item"] = "Base.GuitarElectricBlue",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassRed"] = {
                ["item"] = "Base.GuitarElectricBassRed",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricRed"] = {
                ["item"] = "Base.GuitarElectricRed",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Trumpet"] = {
                ["item"] = "Base.Trumpet",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Violin"] = {
                ["item"] = "Base.Violin",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Banjo"] = {
                ["item"] = "Base.Banjo",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

        },
        ["ID"] = "a36d83e5-8542-436f-8fb1-65784f08d3bf",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 0,
        ["locations"] = {},
    },

}
return defaultShops