local defaultShops = {
    ["19ed14ff-dfb1-4cdb-b34a-f161699842c6"] = {
        ["name"] = "Miscellaneous",
        ["listings"] = {
            ["Base.AlarmClock2"] = {
                ["item"] = "Base.AlarmClock2",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Battery"] = {
                ["item"] = "Base.Battery",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WristWatch_Left_DigitalBlack"] = {
                ["item"] = "Base.WristWatch_Left_DigitalBlack",
                ["price"] = 4,
                ["buybackRate"] = 0.05,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bowl"] = {
                ["item"] = "Base.Bowl",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PetrolCan"] = {
                ["item"] = "Base.PetrolCan",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Generator"] = {
                ["item"] = "Base.Generator",
                ["price"] = 100,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Hairgel"] = {
                ["item"] = "Base.Hairgel",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ElectronicsMag4"] = {
                ["item"] = "Base.ElectronicsMag4",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Lighter"] = {
                ["item"] = "Base.Lighter",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeBomb"] = {
                ["item"] = "Base.PipeBomb",
                ["price"] = 200,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeBombSensorV3"] = {
                ["item"] = "Base.PipeBombSensorV3",
                ["price"] = 300,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Woodglue"] = {
                ["item"] = "Base.Woodglue",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Scissors"] = {
                ["item"] = "Base.Scissors",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "19ed14ff-dfb1-4cdb-b34a-f161699842c6",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 5,
        ["locations"] = {},
    },

    ["8d7e0c39-7aba-410a-929e-5f9548e3e170"] = {
        ["name"] = "Medical",
        ["listings"] = {
            ["Base.Bandaid"] = {
                ["item"] = "Base.Bandaid",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bandage"] = {
                ["item"] = "Base.Bandage",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.AlcoholBandage"] = {
                ["item"] = "Base.AlcoholBandage",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Disinfectant"] = {
                ["item"] = "Base.Disinfectant",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Antibiotics"] = {
                ["item"] = "Base.Antibiotics",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 2,
                ["available"] = 2,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PillsAntiDep"] = {
                ["item"] = "Base.PillsAntiDep",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PillsBeta"] = {
                ["item"] = "Base.PillsBeta",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pills"] = {
                ["item"] = "Base.Pills",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.FirstAidKit"] = {
                ["item"] = "Base.FirstAidKit",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HospitalGown"] = {
                ["item"] = "Base.HospitalGown",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "8d7e0c39-7aba-410a-929e-5f9548e3e170",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 140,
        ["locations"] = {},
    },
    ["8703654d-a899-4798-a454-234af1d01efe"] = {
        ["name"] = "Guns",
        ["listings"] = {
            --- Pistols
            ["Base.Pistol"] = {
                ["item"] = "Base.Pistol",
                ["price"] = 70,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pistol2"] = {
                ["item"] = "Base.Pistol2",
                ["price"] = 85,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pistol3"] = {
                ["item"] = "Base.Pistol3",
                ["price"] = 95,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M92FS"] = {
                ["item"] = "MarzGuns.M92FS",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M93R"] = {
                ["item"] = "MarzGuns.M93R",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.HIPOWER"] = {
                ["item"] = "MarzGuns.HIPOWER",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.P226"] = {
                ["item"] = "MarzGuns.P226",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M1911"] = {
                ["item"] = "MarzGuns.M1911",
                ["price"] = 95,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.USP"] = {
                ["item"] = "MarzGuns.USP",
                ["price"] = 95,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.DEAGLE"] = {
                ["item"] = "MarzGuns.DEAGLE",
                ["price"] = 110,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.VP70M"] = {
                ["item"] = "MarzGuns.VP70M",
                ["price"] = 110,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Revolvers
            ["Base.Revolver_Short"] = {
                ["item"] = "Base.Revolver_Short",
                ["price"] = 85,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Revolver"] = {
                ["item"] = "Base.Revolver",
                ["price"] = 100,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Revolver_Long"] = {
                ["item"] = "Base.Revolver_Long",
                ["price"] = 115,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MP412"] = {
                ["item"] = "MarzGuns.MP412",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.DETECTIVE_38"] = {
                ["item"] = "MarzGuns.DETECTIVE_38",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.COLT_SINGLE"] = {
                ["item"] = "MarzGuns.COLT_SINGLE",
                ["price"] = 100,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.SW629"] = {
                ["item"] = "MarzGuns.SW629",
                ["price"] = 105,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.PYTHON"] = {
                ["item"] = "MarzGuns.PYTHON",
                ["price"] = 105,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.RHINO"] = {
                ["item"] = "MarzGuns.RHINO",
                ["price"] = 105,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- SMGs
            ["MarzGuns.MP5K"] = {
                ["item"] = "MarzGuns.MP5K",
                ["price"] = 135,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.TEC9"] = {
                ["item"] = "MarzGuns.TEC9",
                ["price"] = 135,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MAC10"] = {
                ["item"] = "MarzGuns.MAC10",
                ["price"] = 135,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MP5SD"] = {
                ["item"] = "MarzGuns.MP5SD",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.THOMPSON"] = {
                ["item"] = "MarzGuns.THOMPSON",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MP5"] = {
                ["item"] = "MarzGuns.MP5",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MP5A2"] = {
                ["item"] = "MarzGuns.MP5A2",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Shotguns
            ["Base.Shotgun"] = {
                ["item"] = "Base.Shotgun",
                ["price"] = 155,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.DoubleBarrelShotgun"] = {
                ["item"] = "Base.DoubleBarrelShotgun",
                ["price"] = 140,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ShotgunSawnoff"] = {
                ["item"] = "Base.ShotgunSawnoff",
                ["price"] = 120,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.STEVENS_555"] = {
                ["item"] = "MarzGuns.STEVENS_555",
                ["price"] = 155,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.DOUBLEBARREL"] = {
                ["item"] = "MarzGuns.DOUBLEBARREL",
                ["price"] = 155,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.TOZ34"] = {
                ["item"] = "MarzGuns.TOZ34",
                ["price"] = 155,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MOSSBERG_590"] = {
                ["item"] = "MarzGuns.MOSSBERG_590",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.TRENCHGUN"] = {
                ["item"] = "MarzGuns.TRENCHGUN",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.BENELLI_M4"] = {
                ["item"] = "MarzGuns.BENELLI_M4",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.SPAS12"] = {
                ["item"] = "MarzGuns.SPAS12",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.AA12"] = {
                ["item"] = "MarzGuns.AA12",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.REMINGTON_870"] = {
                ["item"] = "MarzGuns.REMINGTON_870",
                ["price"] = 160,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Bolt-Action Rifles
            ["Base.VarmintRifle"] = {
                ["item"] = "Base.VarmintRifle",
                ["price"] = 90,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HuntingRifle"] = {
                ["item"] = "Base.HuntingRifle",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MODEL_70"] = {
                ["item"] = "MarzGuns.MODEL_70",
                ["price"] = 205,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.REMINGTON_700"] = {
                ["item"] = "MarzGuns.REMINGTON_700",
                ["price"] = 210,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M24"] = {
                ["item"] = "MarzGuns.M24",
                ["price"] = 215,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MOSIN"] = {
                ["item"] = "MarzGuns.MOSIN",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M1903"] = {
                ["item"] = "MarzGuns.M1903",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Lever-Action Rifles
            ["MarzGuns.W1894"] = {
                ["item"] = "MarzGuns.W1894",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.W1873"] = {
                ["item"] = "MarzGuns.W1873",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.W1873_CARBINE"] = {
                ["item"] = "MarzGuns.W1873_CARBINE",
                ["price"] = 150,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.W1887"] = {
                ["item"] = "MarzGuns.W1887",
                ["price"] = 165,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M1895"] = {
                ["item"] = "MarzGuns.M1895",
                ["price"] = 175,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Semi-Auto Rifles
            ["MarzGuns.CAMP_CARBINE"] = {
                ["item"] = "MarzGuns.CAMP_CARBINE",
                ["price"] = 180,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.SVD"] = {
                ["item"] = "MarzGuns.SVD",
                ["price"] = 195,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.SKS"] = {
                ["item"] = "MarzGuns.SKS",
                ["price"] = 195,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.PSG1"] = {
                ["item"] = "MarzGuns.PSG1",
                ["price"] = 195,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.MINI_14"] = {
                ["item"] = "MarzGuns.MINI_14",
                ["price"] = 200,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Battle Rifles
            ["MarzGuns.FAL"] = {
                ["item"] = "MarzGuns.FAL",
                ["price"] = 235,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M14"] = {
                ["item"] = "MarzGuns.M14",
                ["price"] = 240,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.G3"] = {
                ["item"] = "MarzGuns.G3",
                ["price"] = 245,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M1_GARAND"] = {
                ["item"] = "MarzGuns.M1_GARAND",
                ["price"] = 250,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Assault Rifles
            ["Base.AssaultRifle"] = {
                ["item"] = "Base.AssaultRifle",
                ["price"] = 220,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.AssaultRifle2"] = {
                ["item"] = "Base.AssaultRifle2",
                ["price"] = 210,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.XM177"] = {
                ["item"] = "MarzGuns.XM177",
                ["price"] = 220,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M4A1"] = {
                ["item"] = "MarzGuns.M4A1",
                ["price"] = 220,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.G36C"] = {
                ["item"] = "MarzGuns.G36C",
                ["price"] = 220,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.G36"] = {
                ["item"] = "MarzGuns.G36",
                ["price"] = 220,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M16A1"] = {
                ["item"] = "MarzGuns.M16A1",
                ["price"] = 225,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.AR15"] = {
                ["item"] = "MarzGuns.AR15",
                ["price"] = 225,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.CAR15"] = {
                ["item"] = "MarzGuns.CAR15",
                ["price"] = 225,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.ASVAL"] = {
                ["item"] = "MarzGuns.ASVAL",
                ["price"] = 225,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.FAMAS"] = {
                ["item"] = "MarzGuns.FAMAS",
                ["price"] = 225,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M16A2"] = {
                ["item"] = "MarzGuns.M16A2",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M16A2_M203"] = {
                ["item"] = "MarzGuns.M16A2_M203",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M16A3"] = {
                ["item"] = "MarzGuns.M16A3",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.FNC"] = {
                ["item"] = "MarzGuns.FNC",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.AKS74U"] = {
                ["item"] = "MarzGuns.AKS74U",
                ["price"] = 230,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.AK74"] = {
                ["item"] = "MarzGuns.AK74",
                ["price"] = 245,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.AK47"] = {
                ["item"] = "MarzGuns.AK47",
                ["price"] = 250,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Light Machine Guns
            ["MarzGuns.BAR"] = {
                ["item"] = "MarzGuns.BAR",
                ["price"] = 360,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.M60"] = {
                ["item"] = "MarzGuns.M60",
                ["price"] = 430,
                ["buybackRate"] = 0,
                ["stock"] = 4,
                ["available"] = 4,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Firearm Accessories
            ["Base.Glasses_Shooting"] = {
                ["item"] = "Base.Glasses_Shooting",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HolsterSimple"] = {
                ["item"] = "Base.HolsterSimple",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Gloves_LeatherGloves"] = {
                ["item"] = "Base.Gloves_LeatherGloves",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.HolsterDouble"] = {
                ["item"] = "Base.HolsterDouble",
                ["price"] = 40,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Ammunition
            ["Base.Bullets9mmBox"] = {
                ["item"] = "Base.Bullets9mmBox",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets38Box"] = {
                ["item"] = "Base.Bullets38Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets45Box"] = {
                ["item"] = "Base.Bullets45Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bullets44Box"] = {
                ["item"] = "Base.Bullets44Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.223Box"] = {
                ["item"] = "Base.223Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.308Box"] = {
                ["item"] = "Base.308Box",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19_Box"] = {
                ["item"] = "MarzGuns.9x19_Box",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.38_Box"] = {
                ["item"] = "MarzGuns.38_Box",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.45_Box"] = {
                ["item"] = "MarzGuns.45_Box",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x39_Box"] = {
                ["item"] = "MarzGuns.9x39_Box",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.545x39_Box"] = {
                ["item"] = "MarzGuns.545x39_Box",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.44_Box"] = {
                ["item"] = "MarzGuns.44_Box",
                ["price"] = 18,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.357_Box"] = {
                ["item"] = "MarzGuns.357_Box",
                ["price"] = 18,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.50_Box"] = {
                ["item"] = "MarzGuns.50_Box",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.556Box"] = {
                ["item"] = "Base.556Box",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ShotgunShellsBox"] = {
                ["item"] = "Base.ShotgunShellsBox",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.223_Box"] = {
                ["item"] = "MarzGuns.223_Box",
                ["price"] = 22,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.556x45_Box"] = {
                ["item"] = "MarzGuns.556x45_Box",
                ["price"] = 22,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x39_Box"] = {
                ["item"] = "MarzGuns.762x39_Box",
                ["price"] = 22,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.3030_Box"] = {
                ["item"] = "MarzGuns.3030_Box",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.4570_Box"] = {
                ["item"] = "MarzGuns.4570_Box",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.12Gauge_Box_Buckshot"] = {
                ["item"] = "MarzGuns.12Gauge_Box_Buckshot",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.308_Box"] = {
                ["item"] = "MarzGuns.308_Box",
                ["price"] = 26,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51_Box"] = {
                ["item"] = "MarzGuns.762x51_Box",
                ["price"] = 26,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x54_Box"] = {
                ["item"] = "MarzGuns.762x54_Box",
                ["price"] = 26,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.3006_Box"] = {
                ["item"] = "MarzGuns.3006_Box",
                ["price"] = 26,
                ["buybackRate"] = 0,
                ["stock"] = 6,
                ["available"] = 6,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            --- Magazines & Clips
            ["Base.9mmClip"] = {
                ["item"] = "Base.9mmClip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.45Clip"] = {
                ["item"] = "Base.45Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.44Clip"] = {
                ["item"] = "Base.44Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.223Clip"] = {
                ["item"] = "Base.223Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.308Clip"] = {
                ["item"] = "Base.308Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.M14Clip"] = {
                ["item"] = "Base.M14Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.556Clip"] = {
                ["item"] = "Base.556Clip",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 5,
                ["available"] = 5,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51Magazine5_PSG1"] = {
                ["item"] = "MarzGuns.762x51Magazine5_PSG1",
                ["price"] = 15,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine10_P226"] = {
                ["item"] = "MarzGuns.9x19Magazine10_P226",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.45Magazine7_M1911"] = {
                ["item"] = "MarzGuns.45Magazine7_M1911",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.50Magazine8_DEAGLE"] = {
                ["item"] = "MarzGuns.50Magazine8_DEAGLE",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x54Magazine10_SVD"] = {
                ["item"] = "MarzGuns.762x54Magazine10_SVD",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.3006Clip8"] = {
                ["item"] = "MarzGuns.3006Clip8",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.12GMagazine8_AA12"] = {
                ["item"] = "MarzGuns.12GMagazine8_AA12",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine13_HIPOWER"] = {
                ["item"] = "MarzGuns.9x19Magazine13_HIPOWER",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.45Magazine12_USP"] = {
                ["item"] = "MarzGuns.45Magazine12_USP",
                ["price"] = 25,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine15_M92FS"] = {
                ["item"] = "MarzGuns.9x19Magazine15_M92FS",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine18_M93R"] = {
                ["item"] = "MarzGuns.9x19Magazine18_M93R",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine18_VP70M"] = {
                ["item"] = "MarzGuns.9x19Magazine18_VP70M",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine20_MP5"] = {
                ["item"] = "MarzGuns.9x19Magazine20_MP5",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x19Magazine20_TEC9"] = {
                ["item"] = "MarzGuns.9x19Magazine20_TEC9",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.223Magazine20_Mini14"] = {
                ["item"] = "MarzGuns.223Magazine20_Mini14",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.556x45Magazine20_STANAG"] = {
                ["item"] = "MarzGuns.556x45Magazine20_STANAG",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51Magazine20_FAL"] = {
                ["item"] = "MarzGuns.762x51Magazine20_FAL",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51Magazine20_G3"] = {
                ["item"] = "MarzGuns.762x51Magazine20_G3",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51Magazine20_M14"] = {
                ["item"] = "MarzGuns.762x51Magazine20_M14",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.3006Magazine20_BAR"] = {
                ["item"] = "MarzGuns.3006Magazine20_BAR",
                ["price"] = 35,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.45Magazine30_MAC10"] = {
                ["item"] = "MarzGuns.45Magazine30_MAC10",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.45Magazine30_THOMPSON"] = {
                ["item"] = "MarzGuns.45Magazine30_THOMPSON",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.9x39Magazine30"] = {
                ["item"] = "MarzGuns.9x39Magazine30",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.545x39Magazine30_Bakelite"] = {
                ["item"] = "MarzGuns.545x39Magazine30_Bakelite",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.556x45Magazine30_G36"] = {
                ["item"] = "MarzGuns.556x45Magazine30_G36",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.556x45Magazine30_STANAG"] = {
                ["item"] = "MarzGuns.556x45Magazine30_STANAG",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x39Magazine30"] = {
                ["item"] = "MarzGuns.762x39Magazine30",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["MarzGuns.762x51Box100_M60"] = {
                ["item"] = "MarzGuns.762x51Box100_M60",
                ["price"] = 130,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "8703654d-a899-4798-a454-234af1d01efe",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["57094824-711a-436a-869d-030e23ebb3b9"] = {
        ["name"] = "Food and Drink",
        ["listings"] = {
            ["Base.WaterBottleFull"] = {
                ["item"] = "Base.WaterBottleFull",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Apple"] = {
                ["item"] = "Base.Apple",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Bread"] = {
                ["item"] = "Base.Bread",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BeerBottle"] = {
                ["item"] = "Base.BeerBottle",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BeefJerky"] = {
                ["item"] = "Base.BeefJerky",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Banana"] = {
                ["item"] = "Base.Banana",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.CannedChili"] = {
                ["item"] = "Base.CannedChili",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Crisps2"] = {
                ["item"] = "Base.Crisps2",
                ["price"] = 2,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ChickenNuggets"] = {
                ["item"] = "Base.ChickenNuggets",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Corn"] = {
                ["item"] = "Base.Corn",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Chocolate"] = {
                ["item"] = "Base.Chocolate",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.DoughnutFrosted"] = {
                ["item"] = "Base.DoughnutFrosted",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Orange"] = {
                ["item"] = "Base.Orange",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PopBottle"] = {
                ["item"] = "Base.PopBottle",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PeanutButter"] = {
                ["item"] = "Base.PeanutButter",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pickles"] = {
                ["item"] = "Base.Pickles",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Watermelon"] = {
                ["item"] = "Base.Watermelon",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.TinOpener"] = {
                ["item"] = "Base.TinOpener",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Kettle"] = {
                ["item"] = "Base.Kettle",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Pan"] = {
                ["item"] = "Base.Pan",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.GridlePan"] = {
                ["item"] = "Base.GridlePan",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.IcePick"] = {
                ["item"] = "Base.IcePick",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.MeatCleaver"] = {
                ["item"] = "Base.MeatCleaver",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.KitchenKnife"] = {
                ["item"] = "Base.KitchenKnife",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.RollingPin"] = {
                ["item"] = "Base.RollingPin",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BreadKnife"] = {
                ["item"] = "Base.BreadKnife",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Waffles"] = {
                ["item"] = "Base.Waffles",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PeanutButterSandwich"] = {
                ["item"] = "Base.PeanutButterSandwich",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Milk"] = {
                ["item"] = "Base.Milk",
                ["price"] = 10,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "57094824-711a-436a-869d-030e23ebb3b9",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
        },
    ["32383a4f-0463-45af-8402-fcd016066b25"] = {
        ["name"] = "Building",
        ["listings"] = {
            ["Base.BallPeenHammer"] = {
                ["item"] = "Base.BallPeenHammer",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.ClubHammer"] = {
                ["item"] = "Base.ClubHammer",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Hammer"] = {
                ["item"] = "Base.Hammer",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HammerStone"] = {
                ["item"] = "Base.HammerStone",
                ["price"] = 6,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.WoodAxe"] = {
                ["item"] = "Base.WoodAxe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Saw"] = {
                ["item"] = "Base.Saw",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.BlowTorch"] = {
                ["item"] = "Base.BlowTorch",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WeldingMask"] = {
                ["item"] = "Base.WeldingMask",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.NailsBox"] = {
                ["item"] = "Base.NailsBox",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.SheetMetal"] = {
                ["item"] = "Base.SheetMetal",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Plank"] = {
                ["item"] = "Base.Plank",
                ["price"] = 4,
                ["buybackRate"] = 0,
                ["stock"] = 300,
                ["available"] = 300,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.SmallSheetMetal"] = {
                ["item"] = "Base.SmallSheetMetal",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 200,
                ["available"] = 200,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.WeldingRods"] = {
                ["item"] = "Base.WeldingRods",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 400,
                ["available"] = 400,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Sledgehammer"] = {
                ["item"] = "Base.Sledgehammer",
                ["price"] = 70,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Sledgehammer2"] = {
                ["item"] = "Base.Sledgehammer2",
                ["price"] = 70,
                ["buybackRate"] = 0,
                ["stock"] = 1,
                ["available"] = 1,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.PipeWrench"] = {
                ["item"] = "Base.PipeWrench",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Screwdriver"] = {
                ["item"] = "Base.Screwdriver",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 20,
                ["available"] = 20,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Wrench"] = {
                ["item"] = "Base.Wrench",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Plunger"] = {
                ["item"] = "Base.Plunger",
                ["price"] = 2,
                ["buybackRate"] = 0,
                ["stock"] = 50,
                ["available"] = 50,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
        },
        ["ID"] = "32383a4f-0463-45af-8402-fcd016066b25",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 1,
        ["locations"] = {},
    },

    ["a36d83e5-8542-436f-8fb1-65784f08d3bf"] = {
        ["name"] = "Weapons",
        ["listings"] = {
            ["Base.HuntingKnife"] = {
                ["item"] = "Base.HuntingKnife",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Katana"] = {
                ["item"] = "Base.Katana",
                ["price"] = 80,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.LeadPipe"] = {
                ["item"] = "Base.LeadPipe",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Machete"] = {
                ["item"] = "Base.Machete",
                ["price"] = 45,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Axe"] = {
                ["item"] = "Base.Axe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 10,
                ["available"] = 10,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Crowbar"] = {
                ["item"] = "Base.Crowbar",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HandAxe"] = {
                ["item"] = "Base.HandAxe",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HandScythe"] = {
                ["item"] = "Base.HandScythe",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.PickAxe"] = {
                ["item"] = "Base.PickAxe",
                ["price"] = 30,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.SnowShovel"] = {
                ["item"] = "Base.SnowShovel",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.BaseballBat"] = {
                ["item"] = "Base.BaseballBat",
                ["price"] = 24,
                ["buybackRate"] = 0,
                ["stock"] = 30,
                ["available"] = 30,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Golfclub"] = {
                ["item"] = "Base.Golfclub",
                ["price"] = 20,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.HockeyStick"] = {
                ["item"] = "Base.HockeyStick",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.IceHockeyStick"] = {
                ["item"] = "Base.IceHockeyStick",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.LeafRake"] = {
                ["item"] = "Base.LeafRake",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Rake"] = {
                ["item"] = "Base.Rake",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Shovel2"] = {
                ["item"] = "Base.Shovel2",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.Shovel"] = {
                ["item"] = "Base.Shovel",
                ["price"] = 16,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["farming.HandShovel"] = {
                ["item"] = "farming.HandShovel",
                ["price"] = 12,
                ["buybackRate"] = 0,
                ["stock"] = 15,
                ["available"] = 15,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassBlack"] = {
                ["item"] = "Base.GuitarElectricBassBlack",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBlack"] = {
                ["item"] = "Base.GuitarElectricBlack",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassBlue"] = {
                ["item"] = "Base.GuitarElectricBassBlue",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },
            ["Base.GuitarElectricBlue"] = {
                ["item"] = "Base.GuitarElectricBlue",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricBassRed"] = {
                ["item"] = "Base.GuitarElectricBassRed",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.GuitarElectricRed"] = {
                ["item"] = "Base.GuitarElectricRed",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Trumpet"] = {
                ["item"] = "Base.Trumpet",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Violin"] = {
                ["item"] = "Base.Violin",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

            ["Base.Banjo"] = {
                ["item"] = "Base.Banjo",
                ["price"] = 8,
                ["buybackRate"] = 0,
                ["stock"] = 3,
                ["available"] = 3,
                ["reselling"] = false,
                ["alwaysShow"] = true,
                ["fields"] = { },
            },

        },
        ["ID"] = "a36d83e5-8542-436f-8fb1-65784f08d3bf",
        ["isBeingManaged"] = false,
        ["restockHrs"] = 1,
        ["nextRestock"] = 1,
        ["managerIDs"] = {
        },
        ["cash"] = 0,
        ["locations"] = {},
    },

}
return defaultShops